from typing import List, Dict, Any, Tuple
from app.schemas.essay import SentencePattern

class ExplanationEngine:
    """
    Deterministic student-friendly explanation engine. Generates reasons, patterns, and explanations
    based strictly on extracted linguistic and statistical features without any LLM calls.
    """

    def generate_sentence_explanation(
        self,
        sent_text: str,
        sent_feats: Dict[str, float],
        doc_feats: Dict[str, float],
        ai_prob: float
    ) -> Tuple[List[SentencePattern], str, str]:
        patterns: List[SentencePattern] = []
        explanation_parts: List[str] = []
        suggestion = ""

        predictability = sent_feats.get('predictability_index', 0.5)
        ttr = sent_feats.get('ttr', 0.5)
        func_ratio = sent_feats.get('function_word_ratio', 0.3)
        trans_ratio = sent_feats.get('transition_word_ratio', 0.0)
        passive = sent_feats.get('passive_voice_indicator', 0.0)
        pronoun_1st = sent_feats.get('pronoun_1st_ratio', 0.0)
        word_count = sent_feats.get('word_count', 0)
        avg_word_len = sent_feats.get('avg_word_length', 4.5)
        entity_density = doc_feats.get('entity_density', 0.0)

        doc_burstiness = doc_feats.get('burstiness', 0.5)

        # 1. Personal Autobiographical Voice
        if pronoun_1st > 0.08:
            explanation_parts.append("Features active personal narrative and first-person reflection, typical of authentic human storytelling.")

        # 2. Formal Transition Marker
        if trans_ratio > 0.06:
            patterns.append(SentencePattern(
                name="Formal Connector",
                description="Uses elevated transitions (e.g., 'furthermore', 'moreover', 'consequently') that create a rigid rhetorical structure."
            ))
            explanation_parts.append("Starts with a formal transitional phrase that introduces a structured, academic rhythm.")
            suggestion = "Try connecting ideas through narrative flow or causal action rather than heavy academic connectors."

        # 3. Predictable / Abstract AI-like Syntax
        if predictability > 0.58 and pronoun_1st == 0:
            patterns.append(SentencePattern(
                name="Formulaic Phrasing",
                description="Syntactic ordering and token distribution align with common automated language models."
            ))
            explanation_parts.append("Uses elevated abstract diction and balanced phrasing commonly generated by automated writing tools.")
            if not suggestion:
                suggestion = "Ground this sentence with concrete, personal details or vivid imagery."

        # 4. Passive Voice Construction
        if passive > 0.5:
            patterns.append(SentencePattern(
                name="Passive Voice",
                description="Employs passive verbs rather than active subject actions."
            ))
            explanation_parts.append("Passive construction removes the personal subject, creating an impersonal, detached tone.")
            if not suggestion:
                suggestion = "Rewrite in the active voice so your personal actions and decisions stand out clearly."

        # 5. Low Vocabulary Variety in Long Sentences
        if ttr < 0.65 and word_count > 14:
            patterns.append(SentencePattern(
                name="Lexical Repetition",
                description="Repeats similar words or grammatical phrases within the sentence."
            ))
            explanation_parts.append("Uses a relatively narrow vocabulary range for a sentence of this length.")

        # 6. Factual / Encyclopedic Sentence Handling
        if entity_density > 0.08 and pronoun_1st == 0:
            explanation_parts.append("Factual and historical context creates structured syntax, which naturally shares statistical similarities with encyclopedic prose.")

        # Fallback explanations based on calculated signal
        if not explanation_parts:
            if ai_prob >= 65:
                explanation_parts.append("Combines elevated formal diction with uniform syntactic structure, producing an AI-like pattern signal.")
            elif ai_prob >= 35:
                explanation_parts.append("Displays standard expository structure with neutral vocabulary; can naturally occur in both human and assisted writing.")
            else:
                explanation_parts.append("Demonstrates natural sentence rhythm, varied vocabulary, and personal authenticity.")

        final_explanation = " ".join(explanation_parts)
        return patterns, final_explanation, suggestion

    def generate_essay_summary(
        self,
        overall_assessment: str,
        confidence: str,
        ai_pattern_signal: float,
        flagged_count: int,
        total_sents: int,
        doc_feats: Dict[str, float]
    ) -> Tuple[str, str, str, List[str]]:
        """
        Generates dynamic 'summary', 'whyThisResult', 'genreObservation', and 'limitations'.
        """
        limitations = [
            "AI detection is pattern-based and cannot prove or disprove who authored the text.",
            "Formal, academic, and encyclopedic human writing often exhibits structural regularity that overlaps with AI patterns.",
            "Short texts under 150 words have higher statistical variance and limited evidence strength.",
            "This analysis is an educational diagnostic tool for essay refinement, not a punitive verdict."
        ]

        total_words = int(doc_feats.get('total_words', 0))
        burstiness = doc_feats.get('burstiness', 0.0)
        pronoun_1st = doc_feats.get('pronoun_1st_ratio', 0.0)
        entity_density = doc_feats.get('entity_density', 0.0)
        trans_ratio = doc_feats.get('transition_word_ratio', 0.0)

        lex_soph = doc_feats.get('lexical_sophistication', 0.0)
        starter_div = doc_feats.get('sentence_starter_diversity', 0.0)
        contra_ratio = doc_feats.get('contraction_ratio', 0.0)
        punct_var = doc_feats.get('punctuation_variety', 0.0)
        pos_entropy = doc_feats.get('pos_distribution_entropy', 0.0)

        # Genre observation
        if entity_density > 0.07 and pronoun_1st < 0.01:
            genre_obs = "Factual / Encyclopedic / Historical"
        elif pronoun_1st > 0.03:
            genre_obs = "Personal Autobiographical Narrative"
        elif trans_ratio > 0.025:
            genre_obs = "Formal Academic / Argumentative"
        else:
            genre_obs = "General Expository"

        if overall_assessment == "Insufficient Evidence":
            summary = "The submitted text is too short (< 50 words) to establish reliable statistical patterns."
            why_this = "Statistical stylometry requires sufficient text length to measure sentence length variance, lexical diversity, and syntactic distributions."
            return summary, why_this, genre_obs, limitations

        # Dynamic Why This Result
        reasons = []
        if burstiness > 0.35:
            reasons.append("high natural sentence length variation (burstiness)")
        elif burstiness < 0.20:
            reasons.append("unusually uniform sentence pacing")

        if pronoun_1st > 0.03:
            reasons.append("strong personal first-person narrative voice")
        elif pronoun_1st == 0 and entity_density > 0.06:
            reasons.append("objective third-person factual references with specific named entities")

        if trans_ratio > 0.025:
            reasons.append("frequent formal transitional connectors ('furthermore', 'moreover')")

        # New NLP feature observations (at most 2 added to reasons)
        new_reasons = []
        if starter_div < 0.40 and starter_div > 0:
            new_reasons.append("low sentence-starter diversity")
        elif starter_div > 0.70:
            new_reasons.append("varied sentence openings")

        if contra_ratio > 0.015:
            new_reasons.append("natural use of contractions")
        elif contra_ratio == 0 and total_words > 50:
            new_reasons.append("consistently formal contraction profile")

        if lex_soph > 0.30:
            new_reasons.append("relatively sophisticated vocabulary")
        if punct_var > 0.40:
            new_reasons.append("varied punctuation usage")
        if pos_entropy > 2.5:
            new_reasons.append("diverse grammatical-category distribution")

        for nr in new_reasons[:2]:
            reasons.append(nr)

        if not reasons:
            reasons.append("balanced structural pacing and standard vocabulary distribution")

        reasons_str = ", ".join(reasons)

        if overall_assessment == "Likely Human":
            summary = f"The essay demonstrates organic human writing patterns with {reasons_str}. {flagged_count} of {total_sents} sentences showed AI-like structural patterns."
            why_this = f"We detected natural stylistic diversity across the {total_words}-word text, including {reasons_str}. These characteristics align strongly with authentic human personal statements."
        elif overall_assessment == "Mostly Human":
            summary = f"The writing is predominantly human with natural voice and {reasons_str}. {flagged_count} of {total_sents} sentences showed elevated structural formality."
            why_this = f"The essay exhibits largely authentic phrasing with occasional formal patterns. In an admissions context, structured prose can occasionally increase pattern scores without indicating AI involvement."
        elif overall_assessment == "Mixed / Uncertain":
            summary = f"The analysis detected conflicting stylistic signals ({reasons_str}). {flagged_count} of {total_sents} sentences exhibited elevated automated pattern characteristics."
            if entity_density > 0.06:
                why_this = "The text contains formal or encyclopedic phrasing with specific factual data. While formal structure can produce AI-like statistical signals, this is also standard for researched human writing. The evidence remains mixed and inconclusive."
            else:
                why_this = "The essay combines organic personal sections with formulaic or highly structured segments. Because the evidence is divided across independent metrics, the system cannot reliably determine whether AI assistance was involved."
        else:  # Likely AI-assisted
            summary = f"Multiple sections display structural uniformity, elevated transition markers, and low sentence rhythm variance ({reasons_str}). {flagged_count} of {total_sents} sentences show strong automated patterns."
            why_this = f"Multiple independent stylometric signals—including uniform syntax and formal abstract vocabulary—consistently align with patterns produced by large language models. However, because detection is probabilistic, this should be reviewed in context."

        return summary, why_this, genre_obs, limitations
